// ==UserScript==
// @name        twitch-chat
// @version     2.4.2
// @description extensions for chat styling
// @license     MIT
// @match       https://www.twitch.tv/*
// @grant       GM_addStyle
// ==/UserScript==

(function(){"use strict";const p=e=>{let n=window.location.href;e(),navigation.addEventListener("navigate",o=>{n!==o.destination.url&&(e(),n=o.destination.url)})};function b(e,n,o){const t=new MutationObserver((a,s)=>{for(const u of a)n(u,s)});return t.observe(e,{childList:!0,subtree:!0,...o}),()=>t.disconnect()}function i({selector:e,target:n=document.body,rejectTimeoutMs:o,signal:t}){return new Promise((a,s)=>{const u=b(n,(_,x)=>{const g=n.querySelector(e);g&&(x.disconnect(),a(g))}),r={timeout:null,abort:null},h=_=>{r.timeout&&clearTimeout(r.timeout),r.abort&&t.removeEventListener("abort",r.abort),u(),s(_)};o>0&&(r.timeout=setTimeout(()=>h(`${i.name} rejected (${o}ms)`),o)),t&&!t.aborted&&(r.abort=()=>h(t.reason),t.addEventListener("abort",r.abort))})}const f=`.chat-line__username{padding:1px 6px;border:2px solid var(--chat-messege-color);border-radius:50px!important;margin-right:5px}.chat-line__message span[aria-hidden=true]{display:none}.chat-line__message .message,span[data-a-target=chat-line-message-body]{color:var(--chat-messege-color)}
`,y=`.chat-line__username:hover{text-decoration:none!important}.chat-line__message--badges span{border-radius:50px!important;padding:12px}.chat-line__message .ffz-badge{background-repeat:no-repeat;margin-right:6px!important;border:1px solid var(--chat-messege-color)}.ffz-emote{margin-top:2px}
`;GM_addStyle(f);let l=!1;i({selector:"#ffz-script",target:document.head,rejectTimeoutMs:1e4}).then(()=>{var e;l=!0,GM_addStyle(y);const n=document.createElement("style");document.head.appendChild(n);const o=n.sheet,t=(e=document.cookie.split(/; /).find(a=>a.includes("name=")))==null?void 0:e.replace("name=","");o?.insertRule(`.chat-line__message:has([data-login="${t}"]) { background: #501919; }`,o.cssRules.length)});const m=e=>{if(Boolean(e.querySelector("br")))return;const n=e.querySelector(l?".chat-line__username":".chat-author__display-name");if(!n)return;const o=getComputedStyle(n).color;if(e.style.setProperty("--chat-messege-color",o),l){n.after(document.createElement("br"));const t=e.querySelector(".chat-line__message--badges");t&&n.after(t)}else{const t=e.querySelector(".chat-line__username-container");t?.after(document.createElement("br"));const a=t?.querySelector(".chat-line__username"),s=t?.firstChild;s&&a?.after(s)}};let c,d;const v=()=>{setInterval(()=>{const e=document.querySelector(".chat-scrollable-area__message-container");e&&e!==d&&(d=e,S())},1e3)},S=async()=>{c&&c.disconnect(),c=new MutationObserver(e=>{for(const n of e){const o=n.addedNodes[0];o instanceof HTMLElement&&(o.querySelector(".chat-line__message")||o.querySelector(".chat-line__message-container"))&&m(o)}}),c.observe(d,{childList:!0,subtree:!0})};p(v),window.addEventListener("click",async()=>{await i({selector:".chat-input-tray__open .chat-line__message",rejectTimeoutMs:1e3});const e=document.querySelectorAll(".chat-input-tray__open .chat-line__message");for(const n of e)m(n)})})();
