// ==UserScript==
// @name        twitch-chat
// @version     2.4.1
// @description extensions for chat styling
// @license     MIT
// @match       https://www.twitch.tv/*
// @grant       GM_addStyle
// ==/UserScript==

(function(){"use strict";const g=t=>{let n=window.location.href;t(),navigation.addEventListener("navigate",a=>{n!==a.destination.url&&(t(),n=a.destination.url)})};function p(t,n,a){const e=new MutationObserver((o,s)=>{for(const d of o)n(d,s)});return e.observe(t,{childList:!0,subtree:!0,...a}),()=>e.disconnect()}function c({selector:t,target:n=document.body,rejectTimeoutMs:a,signal:e}){return new Promise((o,s)=>{const d=p(n,(h,y)=>{const _=n.querySelector(t);_&&(y.disconnect(),o(_))}),r={timeout:null,abort:null},m=h=>{r.timeout&&clearTimeout(r.timeout),r.abort&&e.removeEventListener("abort",r.abort),d(),s(h)};a>0&&(r.timeout=setTimeout(()=>m(`${c.name} rejected (${a}ms)`),a)),e&&!e.aborted&&(r.abort=()=>m(e.reason),e.addEventListener("abort",r.abort))})}const b=`.chat-line__username{padding:1px 6px;border:2px solid var(--chat-messege-color);border-radius:50px!important;margin-right:5px}.chat-line__message span[aria-hidden=true]{display:none}.chat-line__message .message,span[data-a-target=chat-line-message-body]{color:var(--chat-messege-color)}
`,f=`.chat-line__username:hover{text-decoration:none!important}.chat-line__message--badges span{border-radius:50px!important;padding:12px}.chat-line__message .ffz-badge{background-repeat:no-repeat;margin-right:6px!important;border:1px solid var(--chat-messege-color)}.ffz-emote{margin-top:2px}
`;GM_addStyle(b);let l=!1;c({selector:"#ffz-script",target:document.head,rejectTimeoutMs:1e4}).then(()=>{var t;l=!0,GM_addStyle(f);const n=document.createElement("style");document.head.appendChild(n);const a=n.sheet,e=(t=document.cookie.split(/; /).find(o=>o.includes("name=")))==null?void 0:t.replace("name=","");a?.insertRule(`.chat-line__message:has([data-login="${e}"]) { background: #501919; }`,a.cssRules.length)});const u=t=>{if(Boolean(t.querySelector("br")))return;const n=t.querySelector(l?".chat-line__username":".chat-author__display-name");if(!n)return;const a=getComputedStyle(n).color;if(t.style.setProperty("--chat-messege-color",a),l){n.after(document.createElement("br"));const e=t.querySelector(".chat-line__message--badges");e&&n.after(e)}else{const e=t.querySelector(".chat-line__username-container");e?.after(document.createElement("br"));const o=e?.querySelector(".chat-line__username"),s=e?.firstChild;s&&o?.after(s)}};let i;g(async()=>{const t=await c({selector:".chat-scrollable-area__message-container"});i&&i.disconnect(),i=new MutationObserver(n=>{for(const a of n){const e=a.addedNodes[0];e instanceof HTMLElement&&(e.classList.contains("chat-line__message")||e.classList.contains("chat-line__message-container"))&&u(e)}}),i.observe(t,{childList:!0,subtree:!0})}),window.addEventListener("click",async()=>{await c({selector:".chat-input-tray__open .chat-line__message",rejectTimeoutMs:1e3});const t=document.querySelectorAll(".chat-input-tray__open .chat-line__message");for(const n of t)u(n)})})();
